### ISSUE TITLE
Forward Kinematics 

### ISSUE THREAD

**Issue by Picchi94** [Jak-o-Shadows/stewiegough#1]

**Comment by Jak-o-Shadows** [comment]
Sorry Francesco for the late response. As for your original question about why I need the initial guess of the platform for forward kinematics.

I guess the reason is because the newton raphson is solving for the roots of the equation. It also speeds up processing when you give it a good guess - which is often if you are updating with new parameters often.

I realise this is probably too late to be useful - sorry.

**Comment by Picchi94** [comment]
Thanks for the information. Now I have another question, why did you choose an initial guess position like:
a[20, 20, 200, 10, 10, 10]?

Thanks in advance for the reply

**Comment by Jak-o-Shadows** [comment]
I would guess that it matches roughly my setup. So the first three are in millimetres - 20cm sounds about right for my platform height. The others may just be to try and avoid getting stuck at all zero? I'm not too sure.
